- name: Create an install directory where all the configurations, logs and data files will be stored.
  ansible.builtin.file:
    path: ocp-install-dir
    state: directory
    mode: '0755'

- name: Download the script on your system and change the permission to execute
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ocp-power-automation/openshift-install-power/devel/openshift-install-powervs
    dest: ocp-install-dir/openshift-install-power
    mode: '0755'
    force: yes

- name: Install all the required packages/binaries in current directory.
  ansible.builtin.shell: ocp-install-dir/openshift-install-powervs setup

- name: Interactive way to populate the variables file
  ansible.builtin.shell: ocp-install-dir/openshift-install-powervs variables -{{ all_images }}

- name: Create an OpenShift cluster
  # Usage: openshift-install-powervs [command] [<args> [<value>]]
  ansible.builtin.shell: >
    - ocp-install-dir/openshift-install-powervs {{ terraform_action }} \
        -var-file {{ var_file }} \
        -{{ flavor }} \
        -{{ force_destroy }} \
        -{{ ignore_os_checks }} \
        -{{ verbose }} \
        -{{ trace }} \
        -{{ version }}