---

# cluster_name has no default, it must be passed in
cluster_name: "{{ lookup('env', 'CLUSTER_NAME')}}"

# cluster_type has no default, it must be passed in
cluster_type: "{{ lookup('env', 'CLUSTER_TYPE')}}"

# We can't provide a default, there is no single value that would make sense across all providers, and that would not eventually become dated
ocp_version: "{{ lookup('env', 'OCP_VERSION') }}"

# GPU node settings
# Flag to add GPU worker node to cluster. Currently only set up for ROKS clusters
ocp_provision_gpu: "{{ lookup('env', 'OCP_PROVISION_GPU') | default('false', True) }}"

# The number of GPU worker nodes to deploy. Currently only set up for ROKS clusters
gpu_workers: "{{ lookup('env', 'GPU_WORKERS') | default('1', true) }}"

# The name of the gpu worker pool.
gpu_workerpool_name: "{{ lookup('env', 'GPU_WORKERPOOL_NAME') | default('gpu', true) }}"

# What cluster types does this role support
supported_cluster_types:
  - fyre
  - roks
  - rosa
  - powervs

# ROKS defaults
ibmcloud_apikey: "{{ lookup('env', 'IBMCLOUD_APIKEY') }}"
ibmcloud_resourcegroup: "{{ lookup('env', 'IBMCLOUD_RESOURCEGROUP') | default('Default', true) }}"

roks_zone: "{{ lookup('env', 'ROKS_ZONE') | default('lon02', true) }}"
roks_flavor: "{{ lookup('env', 'ROKS_FLAVOR') | default('b3c.16x64.300gb', true) }}"
roks_workers: "{{ lookup('env', 'ROKS_WORKERS') | default('3', true) }}"
roks_flags: "{{ lookup('env', 'ROKS_FLAGS') | default('', true) }}"

# FYRE defaults
fyre_username: "{{ lookup('env', 'FYRE_USERNAME') }}"
fyre_password: "{{ lookup('env', 'FYRE_APIKEY') }}"

fyre_cluster_description: "{{ lookup('env', 'FYRE_CLUSTER_DESCRIPTION') | default('No description provided', true) }}"
fyre_cluster_size: "{{ lookup('env', 'FYRE_CLUSTER_SIZE') | default('large', true) }}"
fyre_product_id: "{{ lookup('env', 'FYRE_PRODUCT_ID') }}"
fyre_quota_type: "{{ lookup('env', 'FYRE_QUOTA_TYPE') | default('quick_burn', true) }}"

# Only used when quota_type == product_group
fyre_worker_count: "{{ lookup('env', 'FYRE_WORKER_COUNT') | default('3', true) }}"
fyre_worker_memory: "{{ lookup('env', 'FYRE_WORKER_MEMORY') | default('16', true) }}"
fyre_worker_cpu: "{{ lookup('env', 'FYRE_WORKER_CPU') | default('64', true) }}"

# ROSA defaults
rosa_token: "{{ lookup('env', 'ROSA_TOKEN') }}"
rosa_cluster_admin_password: "{{ lookup('env', 'ROSA_CLUSTER_ADMIN_PASSWORD') }}"
rosa_compute_nodes: "{{ lookup('env', 'ROSA_COMPUTE_NODES') | default('3', true) }}"


## IBM Cloud ppc64le 
release_ver: "{{ lookup('env', 'RELEASE_VER') | default('4.10', true) }}"
#terraform_action: "{{ lookup('env', 'ACTION' | default('create', true) }}"
# Variables to pass the script openshift-install-powervs
var_file: "{{ lookup('template', 'powervs/variables.tfvars.j2') }}"
flavor: "{{ lookup('env', 'FLAVOR' | default('', true) }}"
#force_destroy: "{{ lookup('env', 'FOREC_DESTROY' | default('0', true) }}"
ignore_os_checks: "{{ lookup('env', 'IGNORE_OS' | default('0', true) }}"
verbose: "{{ lookup('venvars', 'TF_TRACE' | default('0', true) }}"
#all_images: "{{ lookup('env', 'DISPLAY_ALL_IMAGES' | default('0', true) }}"
trace: "{{ lookup('env', 'TRACE' | default('0', true) }}"
version: "{{ lookup('env', 'VERSION' | default('v1.5.0', true) }}"


vars:
  ibmcloud_region: "mon"
  ibmcloud_zone: "mon01"
  service_instance_id: "d7638b97-909b-472a-a82c-2093753afbbe"
  rhel_image_name: "rhel-85-12132021"
  rhcos_image_name: "rhcos-410-02042022"
  system_type: "s922"
  network_name: "ocp-net-montreal-1"
  openshift_install_tarball: "https://mirror.openshift.com/pub/openshift-v4/ppc64le/clients/ocp/4.10.18/openshift-install-linux.tar.gz"
  openshift_client_tarball: "https://mirror.openshift.com/pub/openshift-v4/ppc64le/clients/ocp/4.10.18/openshift-client-linux.tar.gz"
  cluster_id_prefix: "hari-410-1"
  cluster_id: "ocp1"
  cluster_domain: "ibm.com"
  bastion:
    memory: "16" 
    processors: "1"
    count: "1"
  bootstrap:
    memory: "32"
    processors: "0.5"
    count: "1"
  master:
    memory: "32"
    processors: "1"
    count: "3"
  worker:
    memory: "64"
    processors: "1"
    count: "3"
  volume_size: "300"
  storage_type: "none"
  rhel_subscription_username: "{{ lookup('env', 'RHEL_SUBS_USER') }}"
  rhel_subs_password: "{{ lookup('env', 'RHEL_SUBS_PASSWORD') }}"
  pull_secret_file: "{{ lookup('env', 'PULL_SECRET_FILE') }}"